ecommerce_basket:
    path:     /
    defaults: { _controller: EcommerceBundle:Basket:view }

add_basket:
    path:     /add/{id}
    defaults: { _controller: EcommerceBundle:Basket:add }

delete_basket:
    path:     /delete/{id}
    defaults: { _controller: EcommerceBundle:Basket:delete }

ecommerce_delivery:
    path:     /delivery
    defaults: { _controller: EcommerceBundle:Basket:delivery }

ecommerce_validation:
    path:     /validation
    defaults: { _controller: EcommerceBundle:Basket:validation }

delete_address:
    path:     /delivery/address/delete/{id}
    defaults: { _controller: EcommerceBundle:Basket:deleteAddress }
