adminCategory_index:
    path:     /
    defaults: { _controller: "EcommerceBundle:CategoryAdmin:index" }
    methods:  GET

adminCategory_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:CategoryAdmin:show" }
    methods:  GET

adminCategory_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:CategoryAdmin:new" }
    methods:  [GET, POST]

adminCategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:CategoryAdmin:edit" }
    methods:  [GET, POST]

adminCategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:CategoryAdmin:delete" }
    methods:  DELETE
