routingProduct:
    resource: '@EcommerceBundle/Resources/config/routing/routingProduct.yml'
    prefix: /

routingBasket:
    resource: '@EcommerceBundle/Resources/config/routing/routingBasket.yml'
    prefix: /basket

routingOrder:
    resource: '@EcommerceBundle/Resources/config/routing/routingOrder.yml'
    prefix: /order

routingProductAdmin:
    resource: '@EcommerceBundle/Resources/config/routing/routingProductAdmin.yml'
    prefix: /admin/product

routingCategoryAdmin:
    resource: '@EcommerceBundle/Resources/config/routing/routingCategoryAdmin.yml'
    prefix: /admin/category

routingOrderAdmin:
    resource: '@EcommerceBundle/Resources/config/routing/routingOrderAdmin.yml'
    prefix: /admin/order