routingProduct:
    resource: '@EcommerceBundle/Resources/config/routing/routingProduct.yml'
    prefix: /

routingBasket:
    resource: '@EcommerceBundle/Resources/config/routing/routingBasket.yml'
    prefix: /basket