services:
    taxe:
      class: EcommerceBundle\Twig\Extensions\TaxeExtension
      tags:
        - { name: twig.extension }


    redirectListener:
      class: EcommerceBundle\Listener\RedirectListener
      arguments:  ["@service_container", "@session"]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    setNewReference:
      class: EcommerceBundle\Services\GetReference
      arguments:  ["@security.token_storage", "@doctrine.orm.entity_manager"]

    setNewBill:
      class: EcommerceBundle\Services\GetBill
      arguments:  ["@service_container"]

    EcommerceBundle\Form\UserAddressType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]